/* eslint-disable import/no-anonymous-default-export */

export default [
  {
    id: 1,
    category: "dialy",
    activities: [
      {
        name: "Work",
        current: 5,
        previous: 7,
        previousTime: "day",
        backgroundImg: "icon-work.svg",
        backgroundColor: "hsl(15, 100%, 70%)",
      },
      {
        name: "Play",
        current: 1,
        previous: 2,
        previousTime: "day",
        backgroundImg: "icon-play.svg",
        backgroundColor: "hsl(195, 74%, 62%)",
      },
      {
        name: "Study",
        current: 0,
        previous: 1,
        previousTime: "day",
        backgroundImg: "icon-study.svg",
        backgroundColor: "hsl(348, 100%, 68%)",
      },
      {
        name: "Exercise",
        current: 1,
        previous: 1,
        previousTime: "day",
        backgroundImg: "icon-exercise.svg",
        backgroundColor: "hsl(145, 58%, 55%)",
      },
      {
        name: "Social",
        current: 1,
        previous: 3,
        previousTime: "day",
        backgroundImg: "icon-social.svg",
        backgroundColor: "hsl(264, 64%, 52%)",
      },
      {
        name: "Self Care",
        current: 0,
        previous: 1,
        previousTime: "day",
        backgroundImg: "icon-self-care.svg",
        backgroundColor: "hsl(43, 84%, 65%)",
      },
    ],
  },
  {
    id: 2,
    category: "weekly",
    activities: [
      {
        name: "Work",
        current: 32,
        previous: 36,
        previousTime: "week",
        backgroundImg: "icon-work.svg",
        backgroundColor: "hsl(15, 100%, 70%)",
      },
      {
        name: "Play",
        current: 10,
        previous: 8,
        previousTime: "week",
        backgroundImg: "icon-play.svg",
        backgroundColor: "hsl(195, 74%, 62%)",
      },
      {
        name: "Study",
        current: 4,
        previous: 7,
        previousTime: "week",
        backgroundImg: "icon-study.svg",
        backgroundColor: "hsl(348, 100%, 68%)",
      },
      {
        name: "Exercise",
        current: 4,
        previous: 5,
        previousTime: "week",
        backgroundImg: "icon-exercise.svg",
        backgroundColor: "hsl(145, 58%, 55%)",
      },
      {
        name: "Social",
        current: 5,
        previous: 10,
        previousTime: "week",
        backgroundImg: "icon-social.svg",
        backgroundColor: "hsl(264, 64%, 52%)",
      },
      {
        name: "Self Care",
        current: 2,
        previous: 2,
        previousTime: "week",
        backgroundImg: "icon-self-care.svg",
        backgroundColor: "hsl(43, 84%, 65%)",
      },
    ],
  },
  {
    id: 3,
    category: "monthly",
    activities: [
      {
        name: "Work",
        current: 103,
        previous: 128,
        previousTime: "month",
        backgroundImg: "icon-work.svg",
        backgroundColor: "hsl(15, 100%, 70%)",
      },
      {
        name: "Play",
        current: 23,
        previous: 29,
        previousTime: "month",
        backgroundImg: "icon-play.svg",
        backgroundColor: "hsl(195, 74%, 62%)",
      },
      {
        name: "Study",
        current: 13,
        previous: 19,
        previousTime: "month",
        backgroundImg: "icon-study.svg",
        backgroundColor: "hsl(348, 100%, 68%)",
      },
      {
        name: "Exercise",
        current: 11,
        previous: 18,
        previousTime: "month",
        backgroundImg: "icon-exercise.svg",
        backgroundColor: "hsl(145, 58%, 55%)",
      },
      {
        name: "Social",
        current: 21,
        previous: 23,
        previousTime: "month",
        backgroundImg: "icon-social.svg",
        backgroundColor: "hsl(264, 64%, 52%)",
      },
      {
        name: "Self Care",
        current: 7,
        previous: 11,
        previousTime: "month",
        backgroundImg: "icon-self-care.svg",
        backgroundColor: "hsl(43, 84%, 65%)",
      },
    ],
  },
];
